### ISSUE TITLE
Keep getting 'API Rate Limit Exceeded'

### ISSUE THREAD

**Issue by Yegiyan** [jucasoliveira/terminalGPT#45]
Everything appears to have installed correctly, unfortunately I haven't been able to speak to ChatGPT as I keep receiving this error. 

![WindowsTerminal_Wu2bN7QmRt](https://user-images.githubusercontent.com/10064014/216205588-19fedc92-98b0-4db4-a3f0-91502e15cd02.png)

**Comment by jucasoliveira** [comment]
Thanks for the report @Yegiyan , I'll be looking into it!

**Comment by vitalyverkash** [comment]
Same issue

**Comment by kwuite** [comment]
still an issue

**Comment by chenzhenguo** [comment]
i gass  your free api token is  expired，have to pay for api token

**Comment by ChocolateMagnate** [comment]
I also keep having after a fresh installation. Waiting for a minute doesn't help, and I couldn't send a single message with an API token generated minutes ago. 
![image](https://github.com/jucasoliveira/terminalGPT/assets/95221193/baa0d730-4884-4ba9-be34-790002297dca)

**Comment by chenzhenguo** [comment]
邮件发送失败

**Comment by Glydric** [comment]
This problem is equals to the following json response 
```
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
```
a fix might be use custom API endpoint, this might be a new feature

**Comment by chenzhenguo** [comment]
邮件发送失败

**Comment by kromanow94** [comment]
In my case the solution was to add some credit balance in billing page.

**Comment by jucasoliveira** [comment]
Hello @everyone: 

This issue is related to Account <> OpenAI. TerminalGPT uses OpenAI API and the user key(encrypted) to send request and  return an answer. The error message is been returned from OpenAI, so I consider this a non issue of TerminalGPT.

Since this issue where created from old versions, I suggest everyone to update terminalGPT and make new tests to verify if the error still exists.

# Reminder
Before reopen this issue, always try to verify if your openAI account is not blocked or have insufficient funds.

# More to come
This is a good issue to write about troubleshooting, if someone wants to contribute, feel free to do so. ATM I'm working on a new version of terminalGPT, in a new repo, I'll be announcing soon!
